# Generated by Django 5.2.4 on 2025-07-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_clientlogo_contactmessage_designrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
