# Generated by Django 5.2.4 on 2025-08-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_designrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designrequest',
            name='attachment',
        ),
    ]
